insert into roles(rolename) values
('admin'),('teacher'),('user')
go

insert into users(name,username,password,email,image,dob,point,role_id) values
(N'Đặng Nam','dangnam','sdfsdf',N'dangnam13@gmail.com',N'img.png','2000-12-11',0,1),
(N'Đặng Nam','nam1','sdfsd3f',N'dangnamyk@gmail.com',N'img.png','2000-12-11',0,2),
(N'Đặng Nam','teacher','sdfs4df',N'dang1nayk@gmail.com',N'img.png','2000-12-11',0,3),
(N'Usser','user','sdfsd6f',N'dangnam44yk@gmail.com',N'img.png','2000-12-11',0,3)
go

INSERT into game(description,img,namegame) VALUES 
(N'Hãy thử đoán từ vựng được gợi ý bằng hình ảnh và kiểm tra kết quả đằng sau bức ảnh', N'https://ise.edu.vn/wp-content/uploads/2021/08/hoc-tu-vung-bang-flashcard-04-1.jpg', N'Flash Card ')
INSERT into game ([description], [img], [namegame]) VALUES ( NULL, N'https://universityrelations.wvu.edu/files/e6e80efc-5401-413c-a940-b200cd165b1a/877x585?cb=ca69ec804b71e5957ceb9f1aa7fb94a3', N'Scramble')

INSERT into topic(  [description], [img], [nametopic]) VALUES ( NULL, N'https://i.ytimg.com/vi/FpzosqXVLeQ/maxresdefault.jpg', N'Animals')
INSERT into topic (  [description], [img], [nametopic]) VALUES ( NULL, N'https://i.ytimg.com/vi/zHg51jQCIkc/maxresdefault.jpg', N'Plants')
INSERT into topic (  [description], [img], [nametopic]) VALUES ( NULL, N'https://enetviet.edu.vn/wp-content/uploads/2022/06/Education-la-gi-2-e1623658098277.jpg', N'Education')
INSERT into topic (  [description], [img], [nametopic]) VALUES ( NULL, N'https://hoc24.vn/source/pure/school-icon_1647419576.png', N'School')
INSERT into topic (  [description], [img], [nametopic]) VALUES ( NULL, N'https://i.ytimg.com/vi/mUqwKequriw/maxresdefault.jpg', N'Vegetable and Fruit')
INSERT into topic(  [description], [img], [nametopic]) VALUES ( NULL, N'https://media.baamboozle.com/uploads/images/75346/1627154160_55861.jpeg', N'Color')
INSERT into topic (  [description], [img], [nametopic]) VALUES ( NULL, N'https://i.ytimg.com/vi/JcMJ3VHoi-Q/mqdefault.jpg', N'Appearance')
INSERT into topic (  [description], [img], [nametopic]) VALUES ( NULL, N'https://english4u.com.vn/Uploads/files/Sports-1024x600.jpg', N'Sports')



insert into typeword (nametype) values
('Noun'),('Verb'),('Adverb') ,('Adjective'),('Preposition')
go

insert into words(meaning,text,pronunciation,img,sound,type_id,topic_id) values

(N'Con gấu','Bear',N'/bɛr/ ',N'../../../ImgAudio/con gấu.png',N'','1','1'),
(N'Con chim','Bird',N'/bɜrd/',N'../../../ImgAudio/chim.png',N'','1','1'),
(N'Con mèo','Cat',N'/kæt/',N'../../../ImgAudio/mèo.png',N'','1','1'),
(N'Con gà','Chicken',N'/ˈʧɪkən/ ',N'../../../ImgAudio/gà.png',N'','1','1'),
(N'con hắc tinh tinh','Chimpanzee',N'/tʃɪmpənˈzi/',N'../../../ImgAudio/con hắc tinh tinh.png',N'','1','1'),
(N'Con bò','Cow',N'/kaʊ/ ',N'../../../ImgAudio/con bò.png',N'','1','1'),
(N'Con chó','Dog',N'/dɔg/',N'../../../ImgAudio/con chó.png',N'','1','1'),
(N'Cá heo','Dolphin',N'/ˈdɒlfɪn/',N'../../../ImgAudio/cá heo.png',N'','1','1'),
(N'Con lừa','Donkey',N'/ˈdɑǐki/',N'../../../ImgAudio/con lừa.png',N'','1','1'),
(N'Con lươn','Eel',N'/iːl/',N'../../../ImgAudio/con lươn.png',N'','1','1'),
(N'Con voi','Elephant',N'/ˈɛləfənt/',N'../../../ImgAudio/con voi.png',N'','1','1'),
(N'Con cá','Fish',N'/fɪʃ/ ',N'../../../ImgAudio/Con cá.png',N'','1','1'),
(N'con cáo','Fox',N'/fɑːks/',N'../../../ImgAudio/con cáo.png',N'','1','1'),
(N'con hươu cao cổ','Giraffe',N'ʤɪˈrɑːf',N'../../../ImgAudio/hươu cao cổ.png',N'','1','1'),
(N'Con dê','Goat',N'/goʊt/ ',N'../../../ImgAudio/con dê.png',N'','1','1'),
(N'con hà mã','Hippopotamus',N'/ˌhɪpəˈpɑːtəməs/',N'../../../ImgAudio/hà mã.png',N'','1','1'),
(N'Con ngựa','Horse',N'/hɔrs/ ',N'../../../ImgAudio/ngựa.png',N'','1','1'),
(N'Côn trùng','Insect',N'/ˈɪnˌsɛkt/ ',N'../../../ImgAudio/côn trùng.png',N'','1','1'),
(N'con báo đốm','Jaguar',N'/ˈdʒæɡjuər/',N'../../../ImgAudio/báo đốm.png',N'','1','1'),
(N'Sư tử','Lion',N'/ˈlaɪən/ ',N'../../../ImgAudio/sư tử.png',N'','1','1'),
(N'Con khỉ','Monkey',N'/ˈmʌǐki/ ',N'../../../ImgAudio/khỉ.png',N'','1','1'),
(N'Con chuột','Mouse',N'/maʊs/ ',N'../../../ImgAudio/chuột.png',N'','1','1'),
(N'Con bò đực','Ox',N'/ɑks/ ',N'../../../ImgAudio/boduc.png',N'','1','1'),
(N'chim cánh cụt','Penguin',N'/ˈpeǐɡwɪn/',N'../../../ImgAudio/chimcanhcut.png',N'','1','1'),
(N'Con lợn/heo','Pig',N'/pɪg/ ',N'../../../ImgAudio/heo.png',N'','1','1'),
(N'con nhím','Porcupine',N'/ˈpɔːrkjupaɪn/:',N'../../../ImgAudio/nhím.png',N'','1','1'),
(N'Con thỏ','Rabbit',N'/ˈræbət/',N'../../../ImgAudio/rabit.png',N'','1','1'),
(N'con gấu mèo','raccoon',N'rəˈkuːn',N'../../../ImgAudio/gaumeo.png',N'','1','1'),
(N'con tê giác','Rhinoceros',N'/raɪˈnɒsərəs/:',N'../../../ImgAudio/tegiac.png',N'','1','1'),
(N'cá mập','Shark',N'/ʃɑːk/:',N'../../../ImgAudio/camap.png',N'','1','1'),
(N'Con cừu','Sheep •',N'/ʃip/',N'../../../ImgAudio/cừu.png',N'','1','1'),
(N'con sóc','Squirrel',N'/ˈskwɜːrəl/:',N'../../../ImgAudio/sóc.png',N'','1','1'),
(N'cá kiếm','Swordfish',N'/ˈsɔːdfɪʃ/:',N'../../../ImgAudio/cá kiếm.png',N'','1','1'),
(N'Con hổ','Tiger',N'/ˈtaɪgər/ ',N'../../../ImgAudio/Hổ.png',N'','1','1'),
(N'rùa','Turtle',N'/ˈtɜːtl/:',N'../../../ImgAudio/rùa.png',N'','1','1'),
(N'hải mã','Walrus',N'/ˈwɔːlrəs/:',N'../../../ImgAudio/hải mã.png',N'','1','1'),
(N'Cây tổng quán sủi','Alder',N'/’ɔl:də/',N'',N'','1','2'),
(N'Cây táo','Apple tree',N'ˈæpl triː',N'',N'','1','2'),
(N'Cây tần bì','Ash',N'æʃ',N'',N'','1','2'),
(N'Cây sồi','Beech',N't∫/: ',N'',N'','1','2'),
(N' Cây gỗ bu lô','Birch',N't∫/:',N'',N'','1','2'),
(N'Nở hoa','Bloom',N'/blum/ ',N'',N'','1','2'),
(N'Hoa chuông xanh','Bluebell',N'bel/: ',N'',N'','1','2'),
(N'Cây dương xỉ diều hâu','Bracken',N' /’brækən/:',N'',N'','1','2'),
(N'Cành cây','Branch',N'/brænʧ/',N'',N'','1','2'),
(N'Chồi, búp cây','Bud',N'/bʌd/ ',N'',N'','1','2'),
(N'Bó hoa','The bun of flowers –',N'/bʌn ɒv ˈflaʊəz/:',N'',N'','1','2'),
(N'Bụi rậm','Bush',N' /bu∫/:',N'',N'','1','2'),
(N'Hoa mao lương vàng','Buttercup',N' /’bʌtəkʌp/:',N'',N'','1','2'),
(N'Cây xương rồng','Cactus',N' /kæktəs/',N'',N'','1','2'),
(N'Hoa cẩm chướng','Carnation',N' /kɑ:’nei∫n/:',N'',N'','1','2'),
(N'Cây tuyết tùng','Cedar',N'/’si:də/:',N'',N'','1','2'),
(N'Cây anh đào','Cherry tree',N'/ˈʧɛri',N'',N'','1','2'),
(N'Cây dẻ','Chestnut tree',N'/ˈʧɛsnʌt',N'',N'','1','2'),
(N'Hoa cúc','Chrysanthemum',N'/Kri’sænθəməm/:',N'',N'','1','2'),
(N'Cây dừa','Coconut tree',N'/: ˈkəʊkənʌt triː/',N'',N'','1','2'),
(N'Cây ngô','Corn',N'/kɔ:n/:',N'',N'','1','2'),
(N'Hoa nghệ tây','Crocus',N'/’kroukəs/:',N'',N'','1','2'),
(N'Hoa thủy tiên vàng','Daffodil',N'/’dæfədil/:',N'',N'','1','2'),
(N'Hoa thược dược','Dahlia',N'/’deiljə/:',N'',N'','1','2'),
(N'Hoa cúc','Daisy',N'/’deizi/:',N'',N'','1','2'),
(N'Hoa bồ công anh','Dandelion –',N'/’dændilaiən/:',N'',N'','1','2'),
(N'Cây đu','Elm',N'/elm/:',N'',N'','1','2'),
(N'Cây dương xỉ','Fern',N'/fə:n/:',N'',N'','1','2'),
(N'Cây sung','Fig tree',N'/fɪg',N'',N'','1','2'),
(N'Cây Linh sam','Fir',N'/fə:/:',N'',N'','1','2'),
(N'Hoa','Flower',N'/’flauə/:',N'',N'','1','2'),
(N'Hoa lưu ly','Forget-me-not',N'/fəˈgɛtmɪnɒt/:',N'',N'','1','2'),
(N'Hoa mao địa hoàng','Foxglove',N'/’fɔksglʌv/:',N'',N'','1','2'),
(N'Hoa phong lữ','Geranium',N'/dʒi’reinjəm/:',N'',N'','1','2'),
(N'Trồng cỏ','Grass',N'/grɑ:s/:',N'',N'','1','2'),
(N'Cỏ','Grass',N'/græs/',N'',N'','1','2'),
(N'Mọc lên, lớn lên, phát triển','Grow',N'/groʊ/',N'',N'','1','2'),
(N'Cây táo gai','Hawthorn',N'/’hɔ:θɔ:n/:',N'',N'','1','2'),
(N'Cây phỉ','Hazel',N'/’heizl/:',N'',N'','1','2'),
(N'Cây thạch nam','Heather',N'/’heðə/:',N'',N'','1','2'),
(N'Thảo mộc','Herb',N'/hə:b/:',N'',N'','1','2'),
(N'Cây nhựa ruồi','Holly',N'/’hɔli/:',N'',N'','1','2'),
(N'Cây dẻ ngựa','Horse chestnut tree',N'/hɔːs',N'',N'','1','2'),
(N'Cây thường xuân','Ivy',N'/’aivi/:',N'',N'','1','2'),
(N'Lá cây','Leaf',N'/lif/',N'',N'','1','2'),
(N'Hoa loa kèn','Lily',N'/’lili/:',N'',N'','1','2'),
(N'Cây đoan','Lime',N'/laim/:',N'',N'','1','2'),
(N'Cây thích','Maple',N'/’meipl/:',N'',N'','1','2'),
(N'Rêu','Moss',N'/mɔs/:',N'',N'','1','2'),
(N'Nấm','Mushroom',N'/’mʌ∫rum/:',N'',N'','1','2'),
(N'Cây tầm ma','Nettle',N'/’netl/:',N'',N'','1','2'),
(N'Cây sồi','Oak',N'/əʊk/:',N'',N'','1','2'),
(N'Cây ô liu','Olive tree',N'/ˈɒlɪv',N'',N'','1','2'),
(N'Hoa Lan','Orchid',N'/’ɔ: kid/:',N'',N'','1','2'),
(N'Hoa pĕng xê','Pansy',N'/’pænzi/:',N'',N'','1','2'),
(N'Cây lê','Pear tree',N' /peə triː/:',N'',N'','1','2'),
(N'Cây thông','Pine',N'/pain/:',N'',N'','1','2'),
(N'Cây tiêu huyền','Plane',N'/plein/:',N'',N'','1','2'),
(N'Cây mận','Plum tree',N'/plʌm',N'',N'','1','2'),
(N'Cây bạch dương','Poplar',N'/’pɔplə(r)/:',N'',N'','1','2'),
(N'Hoa anh túc','Poppy',N'/’pɔpi/:',N'',N'','1','2'),
(N'Hoa anh thảo','Primrose',N'/’primrouz/:',N'',N'','1','2'),
(N'Rễ cây','Root',N'/rut/',N'',N'','1','2'),
(N'Hoa hồng','Rose',N'/rouz/:',N'',N'','1','2'),
(N'Hạt giống, hạt','Seed',N'/sid/',N'',N'','1','2'),
(N'Cây bụi','Shrub',N'/∫rʌb/:',N'',N'','1','2'),
(N'Hoa giọt tuyết','Snowdrop',N'/’snoudrɔp/:',N'',N'','1','2'),
(N'Cây sung dâu','Sycamore',N'/’sikəmɔ:/:',N'',N'','1','2'),
(N'Gai','Thorn',N'/θɔrn/',N'',N'','1','2'),
(N'Cây cối','Tree',N'/tri/',N'',N'','1','2'),
(N'Thân cây','Trunk',N'/trʌǐk/',N'',N'','1','2'),
(N'Hoa tulip','Tulip',N'/’tju:lip/:',N'',N'','1','2'),
(N'Hoa súng','Waterlily',N'/’wɔ:təlis]/:',N'',N'','1','2'),
(N'Cây liễu rủ','Weeping willow',N'/ˈwiːpɪǐ',N'',N'','1','2'),
(N'Lúa mì','Wheat',N'/wi:t/:',N'',N'','1','2'),
(N'Cây liễu','Willow',N'/’wilou/:',N'',N'','1','2'),
(N'Gỗ','Wood',N'/wʊd/',N'',N'','1','2'),
(N' Cây thủy tùng','Yew',N'/ju:/:',N'',N'','1','2'),
(N'Quả cóc','Ambarella',N'/’æmbə’rælə/',N'',N'','1','3'),
(N'Quả táo','Apple',N'/ˈæpl/',N'',N'','1','3'),
(N'Quả mơ','Apricot',N'/ˈeɪprɪkɒt/',N'',N'','1','3'),
(N'Quả bơ','Avocado',N'/ˌævəˈkɑːdəʊ/',N'',N'','1','3'),
(N'Quả chuối','Banana',N'/bəˈnɑːnə/',N'',N'','1','3'),
(N'Mận miền nam','Bell fruit',N'/bel/ /fruːt/',N'',N'','1','3'),
(N'Quả anh đào','Cherry (noun)',N'/ˈʧɛri/:',N'',N'','1','3'),
(N'Quả dừa','Coconut',N'/ˈkoʊkəˌnʌt/(noun):',N'',N'','1','3'),
(N'Dưa chuột','Cucumber',N'/ˈkjuːkʌmbə(r)/',N'',N'','1','3'),
(N'Quả na','Custard apple',N'/ˈkʌstəd/',N'',N'','1','3'),
(N'Thanh Long','Dragon fruit',N'/ˈdræɡən/',N'',N'','1','3'),
(N'Sầu riêng','Durian',N'/ˈdʊəriən/',N'',N'','1','3'),
(N'Chanh dây','Granadilla',N'/ɡranəˈdɪlə/',N'',N'','1','3'),
(N'Nho','Grape',N'/ɡreɪp/',N'',N'','1','3'),
(N'Ổi','Guava',N'/ˈɡwɑːvə/',N'',N'','1','3'),
(N'Mít','Jackfruit',N'/ˈdʒækfruːt/',N'',N'','1','3'),
(N'Nước quả, nước ép','Juice',N'/ʤus/',N'',N'','1','3'),
(N'Mọng nước','Juicy',N'/ˈʤusi/(adjective):',N'',N'','1','3'),
(N'Tắc','Kumquat',N'/ˈkʌmkwɒt/',N'',N'','1','3'),
(N'Quả chanh vàng','Lemon',N'/ˈlɛmən/(noun):',N'',N'','1','3'),
(N'Quả chanh xanh','Lime',N'/laɪm/(noun):',N'',N'','1','3'),
(N'Quả nhãn','Longan',N'/ˈlɒǐɡ(ə)n/',N'',N'','1','3'),
(N'Vải','Lychee',N'/ˌlaɪˈtʃiː/',N'',N'','1','3'),
(N'Quýt','Mandarin',N'/ˈmændərɪn/',N'',N'','1','3'),
(N'Xoài','Mango',N'/ˈmæǐɡəʊ/',N'',N'','1','3'),
(N'Măng cụt','Mangosteen',N'/ˈmæǐɡəstiːn/',N'',N'','1','3'),
(N'Quả cam','Orange',N'/ˈɔrənʤ/',N'',N'','1','3'),
(N'Đu đủ','Papaya',N'/pəˈpaɪə/',N'',N'','1','3'),
(N'Quả đào','Peach',N'/piːtʃ/',N'',N'','1','3'),
(N'Quả lê','Pear',N'/peə(r)/',N'',N'','1','3'),
(N'Vỏ trái cây','Peel',N'/pil/',N'',N'','1','3'),
(N'Quả hồng','Persimmon',N'/pəˈsɪmən/',N'',N'','1','3'),
(N'Quả thơm','Pineapple',N'/ˈpaɪnæpl/',N'',N'','1','3'),
(N'Mận bắc','Plum',N'/plʌm/',N'',N'','1','3'),
(N'Anh đào','cherry',N'ˈʧɛri',N'',N'','1','3'),
(N'Măng tây','Asparagus',N'/əˈspærəɡəs/',N'',N'','1','3'),
(N'cây húng quế','Basil',N'/ˈbæzl/:',N'',N'','1','3'),
(N'lá nguyệt quế','Bay leaves:',N'beɪ liːvz',N'',N'','1','3'),
(N'giá','Bean sprouts',N'/ˈbiːn',N'',N'','1','3'),
(N'đậu','Bean',N'/bin/',N'',N'','1','3'),
(N'Củ dền','Beet:',N'/biːt/',N'',N'','1','3'),
(N'Ớt chuông','Bell pepper',N'/bɛl',N'',N'','1','3'),
(N'Thảo mộc đắng','Bitter Herb:',N'/ˌbɪt.ə',N'',N'','1','3'),
(N'Bơ','avocado',N'ˌævəʊˈkɑːdəʊ',N'',N'','1','3'),
(N'Bông cải trắng','Broccoli',N'/ˈbrɒkəli/',N'',N'','1','3'),
(N'Bưởi','Pomelo',N'grapefruit',N'',N'','1','3'),
(N'bắp cải','Cabbage',N'/ˈkæbɪdʒ/:',N'',N'','1','3'),
(N'cam','Orange',N'ˈɒrɪnʤ',N'',N'','1','3'),
(N'Cà rốt','Carrot',N'/ˈkærət/(noun):',N'',N'','1','3'),
(N' súp lơ','Cauliflower',N'/ˈkɒliflaʊə(r)/',N'',N'','1','3'),
(N'Cần tây','Celery',N'/ˈsɛləri/',N'',N'','1','3'),
(N'Cần tây','Celery',N'/ˈsɛləri/ ',N'',N'','1','3'),
(N'Màu đen','Black',N' /blæk/',N'',N'','1','4'),
(N'tóc cắt ngang trán',' A fringe',N'ə frɪnʤ',N'',N'','1','5'),
(N'người có mái tóc ngắn',' A short-haired person',N'ə ʃɔːt-heəd ˈpɜːsn',N'',N'','1','5'),
(N' quyến rǜ, hấp dẫn','Attractive',N'/əˈtræktɪv/ (adjective)',N'',N'','3','5'),
(N'em bé, trẻ con','baby',N'/beibi/:',N'',N'','1','5'),
(N'hói','Bald',N'bɔːld',N'',N'','1','5'),
(N'râu','Beard',N'bɪəd',N'',N'','1','5'),
(N'đẹp, xinh đẹp','Beautiful',N'/ˈbjutəfəl/(adjective):',N'',N'','3','5'),
(N'vết bớt','Birthmark',N'ˈbɜːθmɑːk',N'',N'','1','5'),
(N'tóc vàng','Blonde',N'blɒnd',N'',N'','1','5'),
(N'mắt đỏ ngầu','  Bloodshot',N'ˈblʌdʃɒt',N'',N'','1','5'),
(N'thân hình, vóc dáng cơ thể','Body shape',N'/ˈbɑdi ʃeɪp/',N'',N'','1','5'),
(N'mǜi rộng','Broad',N'brɔːd',N'',N'','1','5'),
(N'thu hút, quyến rǜ','Charming',N'/ˈʧɑrmɪǐ/ ',N'',N'','3','5'),
(N'phúng phính','Chubby',N'ˈʧʌbi',N'',N'','1','5'),
(N'Tóc xoăn','Curly',N'ˈkɜːli',N'',N'','1','5'),
(N'dễ thương, đáng yêu','Cute',N'/kjut/',N'',N'','3','5'),
(N'da đen','Dark',N'dɑːk',N'',N'','1','5'),
(N'đôi mắt mộng mơ','Dreamy eyes',N'ˈdriːmi aɪz',N'',N'','1','5'),
(N'xinh xắn','Pretty',N'/ˈprɪti/',N'',N'','3','5'),
(N'hồng hào','Rosy',N'rəʊzi',N'',N'','2','5'),
(N'vàng vọt','Sallow',N'sæləʊ',N'',N'','3','5'),
(N'sẹo','Scar',N'skɑː',N'',N'','1','5'),
(N'cau có','frown',N'fraʊn',N'',N'','1','5'),
(N'lùn','short',N'ʃɔːt',N'',N'','1','5'),
(N'hơi lùn','a little dwarf',N'ə ˈlɪtl dwɔːf',N'',N'','1','5'),
(N'ốm, gầy','thin',N'θɪn',N'',N'','1','5'),
(N'mảnh khảnh','slim',N'slɪm',N'',N'','1','5'),
(N'gầy, mảnh khảnh','thin, slim',N'θɪn, slɪm',N'',N'','1','5'),
(N'cười mỉm','laugh',N'lɑːf',N'',N'','1','5'),
(N'mǜi hếch','every inch',N'ˈɛvri ɪnʧ',N'',N'','1','5'),
(N'mắt lấp lánh','sparkling eyes',N'ˈspɑːklɪŋ aɪz',N'',N'','1','5'),
(N'mặt vuông','square face',N'skweə feɪs',N'',N'','1','5'),
(N'chắc nịch','stocky',N'ˈstɒki',N'',N'','1','5'),
(N'hơi béo','Little overweight',N'ˈlɪtl ˈəʊvəweɪt',N'',N'','1','5'),
(N'mǜi thẳng','straight nose',N'streɪt nəʊz',N'',N'','1','5'),
(N'tóc thẳng','Straight hair',N'streɪt heə',N'',N'','1','5'),
(N'phiền muộn','complex',N'ˈkɒmplɛks',N'',N'','1','5'),
(N'cao','high',N'haɪ',N'',N'','1','5'),
(N'cao dong dỏng','tall and tall',N'tɔːl ænd tɔːl',N'',N'','1','5'),
(N'gầy','thin',N'θɪn',N'',N'','1','5'),
(N'khuôn mặt gầy','skinny face',N'ˈskɪni feɪs',N'',N'','1','5'),
(N'trẻ em ở độ tuổi mới biết đi','Children in toddler age',N'ˈʧɪldrən ɪn ˈtɒdlər eɪʤ',N'',N'','1','5'),
(N'mǜi cao','height',N'haɪt',N'',N'','1','5'),
(N'xấu xí','bad',N'bæd',N'',N'','1','5'),
(N'không chải chuốt, rối xù','uncomplicated, tangled',N'ˌʌnˈkɒmplɪkeɪtɪd, ˈtæŋgld',N'',N'','1','5'),
(N'tóc lượn sóng','hair wave',N'heə weɪv',N'',N'','1','5'),
(N'cân nặng','weight',N'weɪt',N'',N'','1','5'),
(N'hình thể đẹp','Body beatifull',N'bɒdi ˈbjuːtəfʊl',N'',N'','1','5'),
(N'Màu xanh dương','Blue',N'bluː',N'',N'','1','4'),
(N'Màu Vàng','Yellow',N'',N'',N'','1','4'),
(N'Màu xanh nước biển','Bright blue',N'/braɪt bluː/',N'',N'','1','4'),
(N'màu xanh lá cây tươi','Bright green',N'/braɪt griːn/:',N'',N'','1','4'),
(N'màu đỏ sáng','Bright red',N'/braɪt red /:',N'',N'','1','4'),
(N'Màu nâu','Brown',N'/braʊn/',N'',N'','1','4'),
(N'Màu sắc','Color',N'/ˈkʌlər/(noun):',N'',N'','1','4'),
(N'Rực rỡ, nhiều màu sắc','Colorful',N'/ˈkʌlərfəl/(adjective):',N'',N'','1','4'),
(N'Tối (màu)','Dark',N'/dɑrk/(adjective):',N'',N'','1','4'),
(N'Màu Xanh da trời ','Dark blue',N'/dɑːrk bluː/',N'',N'','1','4'),
(N'màu nâu đậm','Dark brown',N'/dɑːrk braʊn/',N'',N'','1','4'),
(N'màu xanh lá cây đậm','Dark green',N'/dɑːrk griːn/',N'',N'','1','4'),
(N'Màu vàng óng','Gold',N'/ gold/ ',N'',N'','1','4'),
(N'Màu xanh lá','Green',N'/grin/',N'',N'','1','4'),
(N'Màu xám','Grey',N'/greɪ/ ',N'',N'','1','4'),
(N'màu xanh da trời nhạt','Light blue',N'/lait bluː/:',N'',N'','1','4'),
(N'màu nâu nhạt','Light brown',N'/lait braʊn /:',N'',N'','1','4'),
(N'màu xanh lá cây nhạt','Light green',N'/lait griːn /:',N'',N'','1','4'),
(N'Sáng (màu)','Light',N'/laɪt/',N'',N'','1','4'),
(N'Màu cam','Orange ˈ',N'/ɔrənʤ/',N'',N'','1','4'),
(N'Sơn, màu vẽ','Paint',N'/peɪnt/',N'',N'','1','4'),
(N'Màu hồng','Pink',N'/pɪǐk/',N'',N'','1','4'),
(N'Màu tím','Purple',N'/ˈpɜrpəl/',N'',N'','1','4'),
(N'Màu đỏ','Red',N'/rɛd/ ',N'',N'','1','4'),
(N'Sắc độ','Shade',N'/ʃeɪd/ ',N'',N'','1','4'),
(N'Màu trắng','White',N'/waɪt/',N'',N'','1','4'),
(N'Màu vàng','Yellow ˈ',N'/jɛloʊ/ ',N'',N'','1','4')
go

insert into questions (question, answer1,answer2,answer3,word_id) values
(N'Động vật trung thành với chủ là ?', N'Dog',N'Cat','Fish',7),
(N'Động vật có vú tai dài, ăn cỏ, chu kì sinh sản ngắn',N'Rabbit',N'Ox',N'Buffalo',27),
(N'Bộ phận quan trọng ảnh hưởng tới sự sống cây',N'Root',N'leaf',N'trunk',99),
(N'Loại trái cây có vị chua',N'Apple',N'Banana',N'Apricot',177)
